services:
  # Redis 服务，用于缓存、会话管理等，提供键值存储功能
  myreel-redis:
    container_name: myreel-redis
    image: redis:bookworm
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - myreel

  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  myreel-mysql:
    container_name: myreel-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - myreel
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  myreel:
    driver: bridge
    name: myreel