services:
  # Redis 服务，用于缓存、会话管理等，提供键值存储功能
  myreel-redis:
    container_name: myreel-redis
    image: redis:bookworm
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - myreel

  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  myreel-mysql:
    container_name: myreel-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - myreel
    volumes:
      - ./data/mysql:/var/lib/mysql

    # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  myreel-etcd:
    container_name: myreel-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - ./data/etcd:/etcd-data
    networks:
      - myreel
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]

  

networks:
  myreel:
    driver: bridge
    name: myreel